name: Automated Test Build (Server Mode)

on:
  push:
    branches: [ "server" ]
  pull_request:
    branches: [ "server" ]

jobs:
  prepare-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch ocgcore
      uses: actions/checkout@v6
      with:
        repository: mycard/ygopro-core
        path: ocgcore
        ref: master

    - name: Fetch Irrlicht
      uses: actions/checkout@v6
      with:
        repository: mercury233/irrlicht
        path: irrlicht

    - name: Download libevent
      id: libevent
      uses: mercury233/action-cache-download-file@3fffc760bf7b992889fcadf1055bc475b1cd7db6
      with:
        url: https://github.com/libevent/libevent/releases/download/release-2.1.13-stable/libevent-2.1.13-stable.tar.gz
        filename: libevent.tar.gz
        sha256: f7e9383b8c0baa81b687e5b5eecc01beefaf1b19b64151d95ed61647fe7a315c

    - name: Extract libevent
      run: |
        tar xf ${{ steps.libevent.outputs.filepath }}
        mv libevent-2.1.13-stable event

    - name: Download lua
      id: lua
      uses: mercury233/action-cache-download-file@3fffc760bf7b992889fcadf1055bc475b1cd7db6
      with:
        url: https://www.lua.org/ftp/lua-5.4.8.tar.gz
        sha256: 4f18ddae154e793e46eeab727c59ef1c0c0c2b744e7b94219710d76f530629ae

    - name: Extract lua
      run: |
        tar xf ${{ steps.lua.outputs.filepath }}
        mv lua-5.4.8 lua

    - name: Download sqlite
      id: sqlite
      uses: mercury233/action-cache-download-file@3fffc760bf7b992889fcadf1055bc475b1cd7db6
      with:
        url: https://www.sqlite.org/2026/sqlite-amalgamation-3530300.zip
        sha256: 646421e12aac110282ef8cc68f1a62d4bb15fc7b8f09da0b53e29ee690500431

    - name: Extract sqlite
      run: |
        7z x ${{ steps.sqlite.outputs.filepath }}
        mv sqlite-amalgamation-3530300 sqlite3

    - name: Download lzma (xz)
      id: lzma
      uses: mercury233/action-cache-download-file@3fffc760bf7b992889fcadf1055bc475b1cd7db6
      with:
        url: https://github.com/tukaani-project/xz/releases/download/v5.8.3/xz-5.8.3.tar.gz
        sha256: 3d3a1b973af218114f4f889bbaa2f4c037deaae0c8e815eec381c3d546b974a0

    - name: Extract lzma
      run: |
        tar xf ${{ steps.lzma.outputs.filepath }}
        mv xz-5.8.3 lzma

    - name: Download zlib
      id: zlib
      uses: mercury233/action-cache-download-file@3fffc760bf7b992889fcadf1055bc475b1cd7db6
      with:
        url: https://github.com/madler/zlib/releases/download/v1.3.2/zlib-1.3.2.tar.gz
        sha256: bb329a0a2cd0274d05519d61c667c062e06990d72e125ee2dfa8de64f0119d16

    - name: Extract zlib
      run: |
        tar xf ${{ steps.zlib.outputs.filepath }}
        mv zlib-1.3.2 zlib

    - name: Upload dependencies
      uses: actions/upload-artifact@v6
      with:
        name: server-dependencies
        path: |
          event/
          lua/
          sqlite3/
          lzma/
          zlib/
          irrlicht/include/
          irrlicht/source/
          !irrlicht/source/Irrlicht/jpeglib/
          !irrlicht/source/Irrlicht/libpng/
          !irrlicht/source/Irrlicht/zlib/
          ocgcore/

  build-windows:
    needs: prepare-dependencies
    strategy:
      fail-fast: false
      matrix:
        name:
          - windows
          - windows-x64
          - windows-ygopro2-ai-server
#          - windows-2025
        include:
          - name: windows
            os: windows-2022
            vs: vs2022
          - name: windows-x64
            os: windows-2022
            vs: vs2022
            x64: true
#          - name: windows-2025
#            os: windows-2025
#            vs: vs2025 # to be enabled after the release of Visual Studio 2025
          - name: windows-ygopro2-ai-server
            os: windows-2022
            vs: vs2022
            x64: true
            ygopro2: true

    runs-on: ${{ matrix.os }}
    env:
      BUILD_ALL: '1'
      USE_SIMD: server
      SERVER_PRO2_SUPPORT: ${{ matrix.ygopro2 && '1' || '' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 1
        submodules: false

    - name: Download dependencies
      uses: actions/download-artifact@v7
      with:
        name: server-dependencies
        path: .

    - name: Download premake
      id: premake
      uses: mercury233/action-cache-download-file@3fffc760bf7b992889fcadf1055bc475b1cd7db6
      with:
        url: https://github.com/premake/premake-core/releases/download/v5.0.0-beta8/premake-5.0.0-beta8-windows.zip
        filename: premake5.zip
        sha256: e64ce2ed8778e0098f63674cca61fe33941b5f0c8d9a4afd651152bdea3758ab

    - name: Extract premake
      run: |
        7z x ${{ steps.premake.outputs.filepath }}

    - name: Configure libevent
      shell: bash
      run: |
        cp premake/event/msvc-event-config.h event/include/event2/event-config.h
        cp event/WIN32-Code/nmake/evconfig-private.h event/include/evconfig-private.h

    - name: Copy premake files
      run: |
        xcopy /E premake\* .
        xcopy /E resource\* .

    - name: Use premake to generate Visual Studio solution
      run: |
        .\premake5.exe ${{ matrix.vs }}

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v3

    - name: Build solution
      run: |
        MSBuild.exe build\YGOPro.sln /m /p:Configuration=Release /p:Platform=${{ matrix.x64 && 'x64' || 'Win32' }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v6
      with:
        name: YGOPro-Server-${{ matrix.name }}
        path: |
          bin/release/x86/ygopro.exe
          bin/release/x64/ygopro.exe
          bin/release/x64/AI.Server.exe

  build-linux:
    needs: prepare-dependencies
    strategy:
      fail-fast: false
      matrix:
        name:
          - ubuntu-22
          - ubuntu-24
          - ubuntu-static-link
          - ubuntu-zip-support
        include:
          - name: ubuntu-22
            os: ubuntu-22.04
          - name: ubuntu-24
            os: ubuntu-24.04
          - name: ubuntu-static-link
            os: ubuntu-22.04
            static-link: true
          - name: ubuntu-zip-support
            os: ubuntu-22.04
            zip-support: true

    runs-on: ${{ matrix.os }}
    env:
      USE_SIMD: server
      SERVER_ZIP_SUPPORT: ${{ matrix.zip-support && '1' || '' }}
      BUILD_EVENT: ${{ matrix.static-link && '1' || '' }}
      BUILD_SQLITE: ${{ matrix.static-link && '1' || '' }}
      BUILD_LZMA: ${{ matrix.static-link && '1' || '' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 1
        submodules: false

    - name: Download dependencies
      uses: actions/download-artifact@v7
      with:
        name: server-dependencies
        path: .

    - name: Install dependencies
      if: matrix.static-link != true
      run: |
        sudo apt-get update
        sudo apt-get install -y libevent-dev libsqlite3-dev liblzma-dev

    - name: Download premake
      id: premake
      uses: mercury233/action-cache-download-file@3fffc760bf7b992889fcadf1055bc475b1cd7db6
      with:
        url: https://github.com/premake/premake-core/releases/download/v5.0.0-beta8/premake-5.0.0-beta8-linux.tar.gz
        filename: premake5.tar.gz
        sha256: 63edd3e7461eebdd45b500a3c7e8ad4e7a67d68f230010f9a97cbb71b4ec59c8

    - name: Extract & test premake
      id: extract-premake
      run: |
        tar xf ${{ steps.premake.outputs.filepath }}
        chmod +x ./premake5
        mkdir premake-test
        cp ./premake5 ./premake-test
        cd ./premake-test
        if ./premake5 --version; then
          echo "premake=ok" >> $GITHUB_OUTPUT
        else
          echo "premake=fail" >> $GITHUB_OUTPUT
        fi
        cd ..

    - name: Fetch premake source (fallback)
      if: steps.extract-premake.outputs.premake != 'ok'
      uses: actions/checkout@v6
      with:
        repository: premake/premake-core
        path: premake-source
        ref: 2ca338a25ed5f6e62d36c9cd70e5f313953c630d

    - name: Build premake (fallback)
      if: steps.extract-premake.outputs.premake != 'ok'
      run: |
        sudo apt-get update
        sudo apt-get install -y uuid-dev
        cd premake-source
        chmod +x ./Bootstrap.sh
        ./Bootstrap.sh
        cp bin/release/premake5 ../premake5
        cd ..

    - name: Configure libevent
      if: matrix.static-link == true
      run: |
        cd event
        chmod +x configure build-aux/*
        ./configure --disable-openssl --enable-static=yes --enable-shared=no
        sed -f make-event-config.sed < config.h > ./include/event2/event-config.h
        cd ..

    - name: Copy premake files
      run: |
        cp -r premake/* .
        cp -r resource/* .

    - name: Use premake to generate make files
      run: |
        ./premake5 gmake

    - name: Make
      run: |
        cd build
        make -j 4 config=release
        cd ..

    - name: Upload build artifacts
      uses: actions/upload-artifact@v6
      with:
        name: YGOPro-Server-${{ matrix.name }}
        path: |
          bin/release/ygopro

  publish:
    needs: [build-windows]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v7
      with:
        pattern: YGOPro-Server-windows-* # the "windows" (no hyphen) artifact is ignored
        merge-multiple: true

    - name: GitHub Release
      uses: mercury233/action-automatic-releases@cede8e280e06bec07167beaa866ef90277d68303
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "server-latest"
        prerelease: true
        title: "Development Build (Server Mode)"
        files: |
          x64/ygopro.exe
          x64/AI.Server.exe
